# Frames and common
global_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: odom
    robot_base_frame: base_footprint
    update_frequency: 5.0
    publish_frequency: 2.0
    transform_tolerance: 0.3
    rolling_window: true
    width: 10.0
    height: 10.0
    resolution: 0.05
    footprint: [[0.16,0.12],[0.16,-0.12],[-0.16,-0.12],[-0.16,0.12]]
    plugins: ["inflation_layer"]
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.6

local_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: odom
    robot_base_frame: base_footprint
    update_frequency: 10.0
    publish_frequency: 5.0
    transform_tolerance: 0.3
    rolling_window: true
    width: 6.0
    height: 6.0
    resolution: 0.05
    footprint: [[0.16,0.12],[0.16,-0.12],[-0.16,-0.12],[-0.16,0.12]]
    plugins: ["inflation_layer"]
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.6

planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.25

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"
      desired_linear_vel: 0.35
      max_linear_accel: 0.8
      max_angular_accel: 2.0
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9
      use_velocity_scaled_lookahead_dist: true
      rotate_to_heading_angular_vel: 1.0
      transform_tolerance: 0.3
      allow_reversing: false

bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
